# Generated by Django 6.0.4 on 2026-06-09 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='copia_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copias', to='pedagogia.recurso'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='es_plantilla_base',
            field=models.BooleanField(default=False),
        ),
    ]
