$env:Path = $env:Path + ";C:\Program Files\GitHub CLI"
$repo = "ISPC-TSDWAD/ModPWeb--Dev6"
$milestone = "Sprint 2 - Evidencia 3: Integración Completa"

# --- GONZALO (g0niii) - Backend ---
gh issue create -R $repo --title "Backend: Autenticacion JWT" --body "**Asignado a:** Gonzalo Velasco`n**Rama:** feature/issue-01`n`n### Descripcion`nImplementar djangorestframework-simplejwt. Crear endpoints de login (/api/token/) y refresh (/api/token/refresh/). Proteger los ViewSets existentes con IsAuthenticated.`n`n### Criterios de aceptacion`n- Endpoint /api/token/ devuelve access y refresh token con credenciales validas`n- Endpoints protegidos rechazan peticiones sin token (401)`n- Token refresh funciona correctamente" --assignee g0niii --milestone $milestone --label "backend,sprint-2"

gh issue create -R $repo --title "Backend: CRUD Usuarios completo" --body "**Asignado a:** Gonzalo Velasco`n**Rama:** feature/issue-02`n`n### Descripcion`nAsegurar que el ViewSet de Usuarios permita Create, Read, Update, Delete con validaciones y permisos. Endpoint: /api/usuarios/.`n`n### Criterios de aceptacion`n- GET /api/usuarios/ lista todos los usuarios`n- POST /api/usuarios/ crea un usuario nuevo con validacion`n- PUT /api/usuarios/{id}/ actualiza datos`n- DELETE /api/usuarios/{id}/ elimina usuario" --assignee g0niii --milestone $milestone --label "backend,sprint-2"

gh issue create -R $repo --title "Backend: CRUD Recursos completo con filtros" --body "**Asignado a:** Gonzalo Velasco`n**Rama:** feature/issue-03`n`n### Descripcion`nValidar que el CRUD de Recursos funcione end-to-end con relaciones FK a Categoria, Asignatura y Usuario. Endpoint: /api/recursos/. Incluir filtro por asignatura (?asignatura=X).`n`n### Criterios de aceptacion`n- CRUD completo funcionando con datos persistidos en MySQL`n- Filtro por asignatura operativo`n- Relaciones FK validadas (PROTECT)" --assignee g0niii --milestone $milestone --label "backend,sprint-2"

# --- ALE (Corval-LC) - Frontend ---
gh issue create -R $repo --title "Frontend: Conectar API real (reemplazar mocks)" --body "**Asignado a:** Ale Corva`n**Rama:** feature/issue-04`n`n### Descripcion`nReemplazar todos los metodos mock de api.service.ts por llamadas HTTP reales (this.http.get/post/put/delete) apuntando a los endpoints de Django. Configurar CORS en el backend.`n`n### Criterios de aceptacion`n- getRecursos() consume GET /api/recursos/`n- createResource() consume POST /api/recursos/`n- eliminarRecurso() consume DELETE /api/recursos/{id}/`n- actualizarRecurso() consume PUT /api/recursos/{id}/`n- No quedan datos mock en el servicio" --assignee Corval-LC --milestone $milestone --label "frontend,sprint-2"

gh issue create -R $repo --title "Frontend: UI de CRUD completo en Dashboard" --body "**Asignado a:** Ale Corva`n**Rama:** feature/issue-05`n`n### Descripcion`nAgregar botones y modales para Editar y Eliminar recursos desde la interfaz. Feedback visual al usuario (toast/alerta de exito/error).`n`n### Criterios de aceptacion`n- Boton Editar abre formulario con datos precargados`n- Boton Eliminar pide confirmacion antes de borrar`n- Mensaje de exito/error visible al usuario" --assignee Corval-LC --milestone $milestone --label "frontend,sprint-2"

gh issue create -R $repo --title "Frontend: Manejo de errores HTTP" --body "**Asignado a:** Ale Corva`n**Rama:** feature/issue-06`n`n### Descripcion`nImplementar catchError y retry en el servicio API. Mostrar mensajes de error claros al usuario cuando el backend no responde o devuelve errores.`n`n### Criterios de aceptacion`n- Errores 400/401/404/500 muestran mensaje descriptivo`n- Se implementa retry para errores de red`n- El usuario nunca ve una pantalla en blanco por error" --assignee Corval-LC --milestone $milestone --label "frontend,sprint-2"

gh issue create -R $repo --title "Frontend: Routing avanzado + AuthGuard" --body "**Asignado a:** Ale Corva`n**Rama:** feature/issue-11`n`n### Descripcion`nImplementar AuthGuard con canActivate para proteger rutas. Redireccionar a Login si no hay token. Lazy loading de componentes.`n`n### Criterios de aceptacion`n- Rutas /home y /dashboard redirigen a /login si no hay token`n- Guard verifica token en localStorage`n- Componentes cargan con lazy loading" --assignee Corval-LC --milestone $milestone --label "frontend,sprint-2"

# --- GERARDO (GerLR) - QA ---
gh issue create -R $repo --title "QA: Validaciones avanzadas en formularios" --body "**Asignado a:** Gerardo Romero`n**Rama:** feature/issue-07`n`n### Descripcion`nAgregar validaciones asincronas y sincronas avanzadas. Mensajes de feedback especificos por campo. Deshabilitar boton de envio cuando el form es invalido.`n`n### Criterios de aceptacion`n- Cada campo muestra su mensaje de error especifico`n- Boton de envio deshabilitado hasta que el formulario sea valido`n- Validacion de longitud minima/maxima funcional" --assignee GerLR --milestone $milestone --label "qa,sprint-2"

gh issue create -R $repo --title "QA: Login real contra Backend JWT" --body "**Asignado a:** Gerardo Romero`n**Rama:** feature/issue-08`n`n### Descripcion`nConectar el LoginComponent al endpoint de autenticacion JWT de Django. Guardar el token en localStorage. Implementar flujo completo de autenticacion.`n`n### Criterios de aceptacion`n- Login envia credenciales a /api/token/`n- Token se guarda en localStorage al autenticarse`n- Credenciales invalidas muestran error claro`n- Logout limpia el token" --assignee GerLR --milestone $milestone --label "qa,sprint-2"

# --- DANIELA (DanipSal) - Docs ---
gh issue create -R $repo --title "Docs: Diagrama de Clases del sistema" --body "**Asignado a:** Daniela Salvo`n**Rama:** feature/issue-12`n`n### Descripcion`nCrear el Diagrama de Clases del sistema EduTools que muestre las entidades (Usuario, Categoria, Asignatura, Recurso), sus atributos, metodos y relaciones.`n`n### Criterios de aceptacion`n- Diagrama refleja los 4 modelos del backend`n- Incluye relaciones, cardinalidad y tipos de datos`n- Formato imagen (PNG) subido a docs/" --assignee DanipSal --milestone $milestone --label "documentación,sprint-2"

gh issue create -R $repo --title "Docs: Documento Final ABP" --body "**Asignado a:** Daniela Salvo`n**Rama:** feature/issue-13`n`n### Descripcion`nRedactar el Documento Final de Proyecto ABP en formato Word con normas APA. Incluir introduccion, desarrollo, conclusiones y bibliografia.`n`n### Criterios de aceptacion`n- Documento en formato Word (.docx)`n- Normas APA aplicadas`n- Subido a docs/" --assignee DanipSal --milestone $milestone --label "documentación,sprint-2"

gh issue create -R $repo --title "Docs: Poster del Proyecto" --body "**Asignado a:** Daniela Salvo`n**Rama:** feature/issue-14`n`n### Descripcion`nDisenar el Poster academico del proyecto EduTools para la presentacion final. Incluir problema, solucion, stack tecnologico, resultados y equipo.`n`n### Criterios de aceptacion`n- Poster en formato imagen o PDF`n- Contenido sintetico y visual`n- Subido a docs/" --assignee DanipSal --milestone $milestone --label "documentación,sprint-2"

# --- JONATHAN (JG-UNC) - Lider Tecnico ---
gh issue create -R $repo --title "Docs: Wiki del Repositorio" --body "**Asignado a:** Jonathan Guillen`n**Rama:** feature/issue-09`n`n### Descripcion`nCrear la Wiki en GitHub con: Home (tabla de contenidos), pagina de Historias de Usuario, pagina de Ceremonias Scrum (Daily, Review, Retro), enlaces a documentos. Markdown limpio sin exceso de iconos.`n`n### Criterios de aceptacion`n- Wiki Home con tabla de contenidos navegable`n- Pagina de Historias de Usuario completa`n- Pagina de Ceremonias Scrum" --assignee JG-UNC --milestone $milestone --label "documentación,sprint-2"

gh issue create -R $repo --title "Docs: Actualizar README.md" --body "**Asignado a:** Jonathan Guillen`n**Rama:** feature/issue-10`n`n### Descripcion`nAgregar instrucciones de instalacion del Frontend y Backend, integrantes del equipo y roles, como ejecutar ambos servidores.`n`n### Criterios de aceptacion`n- Instrucciones claras de instalacion Front y Back`n- Listado de integrantes con roles`n- Comandos para ejecutar ambos entornos" --assignee JG-UNC --milestone $milestone --label "documentación,sprint-2"

Write-Host "`n=== TODAS LAS ISSUES CREADAS CON EXITO ==="
